In [1]:
!pip install numpy

In [2]:
#importing necessary libraries
import numpy as np


In [ ]:
#define two features
f1=np.array([1,2,3,4,5])
f2=np.array([1,2,3,4,5])

In [ ]:
#mean centering the data
f1=f1 - np.mean(f1)
f2=f2 - np.mean(f2)

In [46]:
#create a 2D array where each row is a feature
arr=np.array([f1,f2])
arr

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

In [47]:
#calculate covariance matrix
cov=np.cov(arr)
cov

array([[2.5, 2.5],
       [2.5, 2.5]])

In [48]:
#calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov)
eigenvalues, eigenvectors

(array([5.0000000e+00, 4.4408921e-16]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [49]:
#getting index of sorted eigenvalues in descending order
index=np.argsort(eigenvalues)[::-1]

In [50]:
#selecting the eigenvector with the highest eigenvalue
new_bases=eigenvectors[:,0]

In [51]:
arr.T

array([[-2., -2.],
       [-1., -1.],
       [ 0.,  0.],
       [ 1.,  1.],
       [ 2.,  2.]])

In [52]:
#projecting the data onto the new basis
new_feature=np.dot(arr.T,new_bases)
new_feature

array([-2.82842712, -1.41421356,  0.        ,  1.41421356,  2.82842712])